#!/usr/bin/env python3
import subprocess
import sys
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"
_TEST_DIR = _PROGRAM_DIR / "tests"
_CI_TESTS = [
    _TEST_DIR / f"test_{name}.py"
    for name in (
        "hass_api",
        "hassil_fst",
        "models",
        "validate_yaml",
        "g2p",
        "recognize",
    )
]

if _VENV_DIR.exists():
    context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
    python_exe = context.env_exe
else:
    python_exe = "python3"

subprocess.check_call([python_exe, "-m", "pytest"] + _CI_TESTS + sys.argv[1:])
